export const endpoints = {
  login: "/auth/login",
  refresh: "/auth/refresh",
  logout: "/auth/logout",
  me: "/users/me",
  users: "/users",
  user: (id: string) => `/users/${id}`,
  departments: "/departments",
  department: (id: string) => `/departments/${id}`,
  roles: "/roles",
  role: (id: string) => `/roles/${id}`,
  permissions: "/permissions",
  projects: "/projects",
  project: (id: string) => `/projects/${id}`,
  projectMembers: (id: string) => `/projects/${id}/members`,
  projectMember: (projectId: string, userId: string) => `/projects/${projectId}/members/${userId}`,
  projectTasks: (id: string) => `/projects/${id}/tasks`,
  projectActivity: (id: string) => `/projects/${id}/activity`,
  task: (id: string) => `/tasks/${id}`,
  taskDependencies: (id: string) => `/tasks/${id}/dependencies`,
  taskDependency: (taskId: string, depId: string) => `/tasks/${taskId}/dependencies/${depId}`,
  taskComments: (id: string) => `/tasks/${id}/comments`,
  resourcesAllocations: "/resources/allocations",
  resourceAllocation: (id: string) => `/resources/allocations/${id}`,
  resourcesCapacity: "/resources/capacity",
  resourcesMatrix: "/resources/matrix",
  resourcesAvailability: "/resources/availability",
  resourcesOverloadAlerts: "/resources/overload-alerts",
  resourcesHolidays: "/resources/holidays",
  resourceHoliday: (id: string) => `/resources/holidays/${id}`,
  meWorkload: "/me/workload",
  dashboardExecutive: "/dashboards/executive",
  dashboardProjectManager: "/dashboards/project-manager",
  dashboardMember: "/dashboards/member",
  notifications: "/notifications",
  notificationsUnreadCount: "/notifications/unread-count",
  notificationRead: (id: string) => `/notifications/${id}/read`,
  notificationsReadAll: "/notifications/read-all",
  auditLogs: "/audit-logs",
  reportsProjectStatus: "/reports/project-status",
  reportsUtilization: "/reports/resource-utilization",
  reportsTaskCompletion: "/reports/task-completion",
} as const
