export const endpoints = {
  login: "/auth/login",
  refresh: "/auth/refresh",
  logout: "/auth/logout",
  me: "/users/me",
  users: "/users",
  user: (id: string) => `/users/${id}`,
  departments: "/departments",
  department: (id: string) => `/departments/${id}`,
  roles: "/roles",
  projects: "/projects",
  project: (id: string) => `/projects/${id}`,
  projectMembers: (id: string) => `/projects/${id}/members`,
  projectMember: (projectId: string, userId: string) => `/projects/${projectId}/members/${userId}`,
  projectTasks: (id: string) => `/projects/${id}/tasks`,
  projectActivity: (id: string) => `/projects/${id}/activity`,
  task: (id: string) => `/tasks/${id}`,
  taskDependencies: (id: string) => `/tasks/${id}/dependencies`,
  taskDependency: (taskId: string, depId: string) => `/tasks/${taskId}/dependencies/${depId}`,
  taskComments: (id: string) => `/tasks/${id}/comments`,
} as const
